### ISSUE TITLE
TestFlight todo list

### ISSUE THREAD

**Issue by danielnordh** [bdgwallet/dailywallet#17]
Issues to fix before first Test Flight

- [x] Remove jank when tapping Request
- [x] Fix QR scanner not returning
- [ ] Reset amount after send / request
- [ ] Can open channel manually
- [ ] Can open channel with JIT (depending on LSP)
- [x] Pass scanned address/invoice to send view
- [ ] Add disclaimer on settings page
- [ ] Show confirmation / error when paying
- [ ] Split onchain QR data into address, amount etc.
